name: Tweet Bot Automation

on:
  schedule:
    - cron: "0 2,8,14,20 * * *"  # every 6 hours UTC
  workflow_dispatch:        # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: X_API_KEY

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
        run: |
          python tweeter.py
